name: EmptyStudioAI
options:
  bundleIdPrefix: com.emptystudio.ai.emy
targets:
  EmptyStudioAI:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - EmptyStudioAI
    settings:
      CODE_SIGNING_ALLOWED: NO
