name: EmptyStudioAI
options:
  bundleIdPrefix: com.emptystudio.emy
  objectVersion: 56 # Ép XcodeGen sinh file tương thích với Xcode 15
targets:
  EmptyStudioAI:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - EmptyStudioAI
    settings:
      CODE_SIGNING_ALLOWED: NO